 platform :ios, '8.0'

target 'SwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'FSPagerView'
pod 'DGElasticPullToRefresh'
pod 'IQKeyboardManagerSwift'
pod 'SnapKit'
pod 'BaiduMapKit' #百度地图SDK
pod 'JPush'

  # Pods for SwiftProject

end
