 platform :ios, '8.0'

target 'SwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'FSPagerView'
pod 'DGElasticPullToRefresh'
pod 'IQKeyboardManagerSwift'
pod 'SnapKit', '~> 3.0.0'
  # Pods for SwiftProject

end
